apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-react-app
  template:
    metadata:
      labels:
        app: kubernetes-react-app
    spec:
      containers:
      - name: kubernetes-react-app
        image: pedrobear/kubernetes-react-app:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-react-app-service
spec:
  selector:
    app: kubernetes-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer